apiVersion: apps.example.com/v1alpha1
kind: SpringApp
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: springapp-sample
spec:
  image: notes-service:dev
  replicas: 1
  service:
    port: 8080
    type: ClusterIP
  database:
    provider: postgres
    host: postgres.demo.svc.cluster.local
    port: 5432
    name: notesdb
    credentialsSecretRef:
      name: notes-db-secret
  runtime:
    env:
      APP_LOG_LEVEL: INFO
